'Da Bin CHOI': 'Dabin CHOI'
'Kavita LORENZ / Panagiotis POLIZOAKIS': 'Kavita LORENZ / Joti POLIZOAKIS'
'Natalia KALISZEK / Maksim SPODIREV': 'Natalia KALISZEK / Maksym SPODYRIEV'
'Pilar MAEKAWA / Leonardo MAEKAWA': 'Pilar MAEKAWA MORENO / Leonardo MAEKAWA MORENO'
'Elizaveta TUKTAMISHEVA': 'Elizaveta TUKTAMYSHEVA'
'Haejin KIM': 'Hae Jin KIM'
'Min-Jung KWAK': 'Min-Jeong KWAK'
'Na Hyun KIM': 'Nahyun KIM'
'Sandra KOHPON': 'Sandra KHOPON'
'Yu-Na KIM': 'Yuna KIM'
'Evgeny PLYUSHCHENKO': 'Evgeni PLUSHENKO'
'Leslie IP': 'Leslie Man Cheuk IP'
'Elizabeta MAKAROVA / Leri KENCHADZE': 'Elizaveta MAKAROVA / Leri KENCHADZE'
'Maylin HAUSCH / Daniel WENDE': 'Maylin WENDE / Daniel WENDE'
'Natalja ZABIJAKO / Alexander ENBERT': 'Natalia ZABIIAKO / Alexander ENBERT'
'Sumire SUTO / Francis BOUDREAU AUDET': 'Sumire SUTO / Francis BOUDREAU-AUDET'
'Yulia LIPNITSKAYA': 'Julia LIPNITSKAIA'