'Da Bin CHOI': 'Dabin CHOI'
'Kavita LORENZ / Panagiotis POLIZOAKIS': 'Kavita LORENZ / Joti POLIZOAKIS'
'Natalia KALISZEK / Maksim SPODIREV': 'Natalia KALISZEK / Maksym SPODYRIEV'
'Pilar MAEKAWA / Leonardo MAEKAWA': 'Pilar MAEKAWA MORENO / Leonardo MAEKAWA MORENO'
'Elizaveta TUKTAMISHEVA': 'Elizaveta TUKTAMYSHEVA'
'Haejin KIM': 'Hae Jin KIM'
'Min-Jung KWAK': 'Min-Jeong KWAK'
'Na Hyun KIM': 'Nahyun KIM'
'Sandra KOHPON': 'Sandra KHOPON'
'Yu-Na KIM': 'Yuna KIM'
'Evgeny PLYUSHCHENKO': 'Evgeni PLUSHENKO'
'Leslie IP': 'Leslie Man Cheuk IP'
'Elizabeta MAKAROVA / Leri KENCHADZE': 'Elizaveta MAKAROVA / Leri KENCHADZE'
'Maylin HAUSCH / Daniel WENDE': 'Maylin WENDE / Daniel WENDE'
'Natalja ZABIJAKO / Alexander ENBERT': 'Natalia ZABIIAKO / Alexander ENBERT'
'Sumire SUTO / Francis BOUDREAU AUDET': 'Sumire SUTO / Francis BOUDREAU-AUDET'
'Yulia LIPNITSKAYA': 'Julia LIPNITSKAIA'
'van der PERREN Kevin': 'Kevin VAN DER PERREN'
'Jenna McCORKELL': 'Jenna MCCORKELL'
'Dong-Won LEE': 'Dong Won LEE'
'MONICA Nicole DELLA / Yannick KOCON': 'Nicole DELLA MONICA / Yannick KOCON'
'Maria NOSULIA / Evgen KHOLONIUK': 'Maria NOSULIA / Evgeni KHOLONIUK'
'V SINITSINA / R ZHIGANSHIN': 'Victoria SINITSINA / Ruslan ZHIGANSHIN'
'Viktoria KAVALEVA / Yirii BIELIAIEV': 'Viktoria KAVALIOVA / Yurii BIELIAIEV'
'Isabelle M. OLSSON': 'Isabelle OLSSON'
'Julia LAVRENTIEVA / Yuri RUDIK': 'Julia LAVRENTIEVA / Yuri RUDYK'
'MOORE-TOWERS K / D MOSCOVITCH': 'Kirsten MOORE-TOWERS / Dylan MOSCOVITCH'
'Hae-Jin KIM': 'Hae Jin KIM'
'I TOBIAS / D STAGNIUNAS': 'Isabella TOBIAS / Deividas STAGNIUNAS'
'Maria PALYAKOVA / Mikhail FOMICHEV': 'Maria PALIAKOVA / Mikhail FOMICHEV'
'Jin Seo KIM': 'Jinseo KIM'
'HEEKIN-CANEDY Siobhan / Dmitri DUN': 'Siobhan HEEKIN-CANEDY / Dmitri DUN'
'Anna YANOVSKAIA / Sergei MOZGOV': 'Anna YANOVSKAYA / Sergey MOZGOV'
'Kamila GAINETDINOVA / Ivan BICH': 'Kamilla GAINETDINOVA / Ivan BICH'
'Tarah KAYNE / Daniel O SHEA': 'Tarah KAYNE / Danny O'SHEA'
'Maeva GALLARDA': 'Maeva GALLARDA ROSSELL'
'Lubov ILIUSHECHKINA / Dylan MOSCOVITCH': 'Liubov ILYUSHECHKINA / Dylan MOSCOVITCH'
'MONICA N DELLA / M GUARISE': 'Nicole DELLA MONICA / Matteo GUARISE'
'Alexa SCIMECA / Chris KNIERIM': 'Alexa SCIMECA KNIERIM / Chris KNIERIM'
'Elizabet TURZYNBAEVA': 'Elizabet TURSYNBAEVA'
'A DAVIDOVICH / E KRASNOPOLSKI': 'Andrea DAVIDOVICH / Evgeni KRASNOPOLSKI'
'Ho Jung LEE / Richard Kang In KAM': 'Hojung LEE / Richard Kang In KAM'
'Alexandra BORISOVA / Cezary ZAWADZKI': 'Olexandra BORYSOVA / Cezary ZAWADZKI'
'Nicole KUZMICH / Alexandr SINICYN': 'Nicole KUZMICHOVA / Alexandr SINICYN'
